export const AGREGAR_JUEGO = "AGREGAR_JUEGO";
export const AGREGAR_JUEGO_EXITO = "AGREGAR_JUEGO_EXITO";
export const AGREGAR_JUEGO_ERROR = "AGREGAR_JUEGO_ERROR ";

export const OBTENER_JUEGOS_EXITO = "OBTENER_JUEGOS_EXITO";
export const OBTENER_JUEGOS_ERROR = "OBTENER_JUEGOS_ERROR";
