export const AGREGAR_JUEGO = "AGREGAR_JUEGO";
export const AGREGAR_JUEGO_EXITO = "AGREGAR_JUEGO_EXITO";
export const AGREGAR_JUEGO_ERROR = "AGREGAR_JUEGO_ERROR ";

export const OBTENER_JUEGOS = "OBTENER_JUEGOS";
export const OBTENER_JUEGOS_EXITO = "OBTENER_JUEGOS_EXITO";
export const OBTENER_JUEGOS_ERROR = "OBTENER_JUEGOS_ERROR";

export const ELIMINAR_JUEGO_EXITO = "ELIMINAR_JUEGO_EXITO";
export const ELIMINAR_JUEGO_ERROR = "ELIMINAR_JUEGO_ERROR";

export const OBTENER_JUEGO_EDITAR = "OBTENER_PRODUCTO_EDITAR";
export const EDITAR_JUEGO_EXITO = "EDITAR_JUEGO_EXITO";
export const EDITAR_JUEGO_ERROR = "EDITAR_JUEGO_ERROR";
